language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

cache:
  directories:
    - $HOME/.php-cs-fixer

before_script:
  - composer self-update
  - composer update --prefer-source $PREFER_LOWEST
  - mkdir -p test/_build

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/_build/logs/clover.xml
